module.exports = {
  apps: [
    {
      name: 'vito-server',
      script: './node_modules/.bin/tsx',
      args: 'src/index.ts',
      interpreter: '/Users/mike/.nvm/versions/node/v24.13.0/bin/node',
      watch: false,
      env: {
        NODE_ENV: 'production',
      },
      error_file: 'user/logs/pm2-error.log',
      out_file: 'user/logs/pm2-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'cloudflared-tunnel',
      script: 'cloudflared',
      args: 'tunnel --config /Users/mike/.cloudflared/config.yml run vito-services',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: 'user/logs/cloudflared-error.log',
      out_file: 'user/logs/cloudflared-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'notes-app',
      script: '/Users/mike/notes-app/server.js',
      cwd: '/Users/mike/notes-app',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: 'user/logs/notes-app-error.log',
      out_file: 'user/logs/notes-app-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
  ],
};
