module.exports = {
  apps: [
    {
      name: 'vito-server',
      script: './node_modules/.bin/tsx',
      args: 'src/index.ts',
      interpreter: '/Users/mike/.nvm/versions/node/v24.13.0/bin/node',
      watch: false,
      env: {
        NODE_ENV: 'production',
      },
      error_file: 'user/logs/pm2-error.log',
      out_file: 'user/logs/pm2-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'cloudflared-tunnel',
      script: 'cloudflared',
      args: 'tunnel --config /Users/mike/.cloudflared/config.yml run vito-services',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: 'user/logs/cloudflared-error.log',
      out_file: 'user/logs/cloudflared-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'app-notes',
      script: '/Users/mike/notes-app/server.js',
      cwd: '/Users/mike/notes-app',
      interpreter: '/Users/mike/.nvm/versions/node/v24.13.0/bin/node',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: 'user/logs/notes-error.log',
      out_file: 'user/logs/notes-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'app-arc-raiders-loot',
      script: 'server.js',
      cwd: '/Users/mike/vito3.0/user/apps/arc-raiders-loot',
      interpreter: '/Users/mike/.nvm/versions/node/v24.13.0/bin/node',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: 'user/logs/arc-raiders-loot-error.log',
      out_file: 'user/logs/arc-raiders-loot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'app-nutrition-tracker',
      script: 'server.js',
      cwd: '/Users/mike/vito3.0/user/apps/nutrition-tracker',
      interpreter: '/Users/mike/.nvm/versions/node/v24.13.0/bin/node',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: 'user/logs/nutrition-tracker-error.log',
      out_file: 'user/logs/nutrition-tracker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'app-chord-lab',
      script: 'server.js',
      cwd: '/Users/mike/vito3.0/user/apps/chord-lab',
      interpreter: '/Users/mike/.nvm/versions/node/v24.13.0/bin/node',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: 'user/logs/chord-lab-error.log',
      out_file: 'user/logs/chord-lab-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'app-love-songs',
      script: 'server.js',
      cwd: '/Users/mike/vito3.0/user/apps/love-songs',
      interpreter: '/Users/mike/.nvm/versions/node/v24.13.0/bin/node',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: 'user/logs/love-songs-error.log',
      out_file: 'user/logs/love-songs-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
  ],
};
