import { Platform, StyleSheet } from "react-native";
import type { VitoTheme } from "../hooks/useVitoTheme";

export const createAppStyles = (theme: VitoTheme) =>
  StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: theme.colors.canvas },
    voiceScreen: { flex: 1, paddingHorizontal: theme.space.xl, paddingBottom: theme.space.md },
    voiceScreenDesktop: {
      padding: theme.space.xxxl,
      maxWidth: 860,
      width: "100%",
      alignSelf: "center",
    },
    voiceOverlay: {
      position: "absolute",
      left: theme.space.md,
      right: theme.space.md,
      bottom: 78,
      minHeight: 62,
      paddingHorizontal: theme.space.md,
      paddingVertical: theme.space.sm,
      borderRadius: 17,
      flexDirection: "row",
      alignItems: "center",
      gap: theme.space.md,
      backgroundColor: theme.colors.surfaceRaised,
      borderWidth: 1,
      borderColor: theme.colors.separatorStrong,
      shadowColor: "#000",
      shadowOpacity: 0.22,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 8 },
      elevation: 12,
      zIndex: 100,
    },
    voiceOverlayDesktop: {
      left: undefined,
      right: theme.space.xl,
      bottom: theme.space.xl,
      width: 310,
    },
    voicePulse: {
      width: 38,
      height: 38,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.accent,
    },
    voicePulseSpeaking: { transform: [{ scale: 1.05 }] },
    voiceOverlayCopy: { flex: 1, minWidth: 0 },
    voiceOverlayTitle: { color: theme.colors.text, fontSize: 13, fontWeight: "800" },
    voiceOverlayDetail: {
      color: theme.colors.textMuted,
      fontSize: 11,
      marginTop: theme.space.xs,
    },
    voiceReadyDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.colors.accent,
    },
    loading: {
      flex: 1,
      backgroundColor: theme.colors.canvas,
      alignItems: "center",
      justifyContent: "center",
    },
    routeBackground: { backgroundColor: theme.colors.canvas },
    sidebar: {
      width: 224,
      paddingHorizontal: theme.space.lg,
      paddingTop: theme.space.xl,
      paddingBottom: theme.space.lg,
      backgroundColor: theme.colors.sidebar,
      borderRightWidth: 1,
      borderRightColor: theme.colors.separator,
    },
    brand: {
      flexDirection: "row",
      paddingHorizontal: theme.space.md,
      marginBottom: theme.space.xxl,
    },
    brandName: { color: theme.colors.text, fontSize: 19, fontWeight: "800" },
    brandDot: { color: theme.colors.accent, fontSize: 19, fontWeight: "800" },
    desktopNavList: { paddingBottom: theme.space.md },
    navSection: {
      color: theme.colors.textMuted,
      fontSize: 9,
      fontWeight: "800",
      letterSpacing: 1.4,
      textTransform: "uppercase",
      marginTop: theme.space.xl,
      marginBottom: theme.space.sm,
      paddingHorizontal: theme.space.md,
    },
    navItem: {
      minHeight: 36,
      flexDirection: "row",
      alignItems: "center",
      gap: theme.space.md,
      paddingHorizontal: theme.space.md,
    },
    navIcon: { color: theme.colors.textMuted, width: 18 },
    navLabel: { color: theme.colors.textSecondary, fontWeight: "600", fontSize: 13 },
    navLabelActive: { color: theme.colors.text, fontWeight: "800" },
    navActiveDot: {
      marginLeft: "auto",
      width: 5,
      height: 5,
      borderRadius: 3,
      backgroundColor: theme.colors.accent,
    },
    activeText: { color: theme.colors.accent },
    signOut: { padding: theme.space.md, alignItems: "center" },
    signOutText: { color: theme.colors.textMuted, fontSize: 11, fontWeight: "700" },
    tabBar: {
      backgroundColor: theme.colors.sidebar,
      borderTopWidth: 1,
      borderTopColor: theme.colors.separator,
      paddingBottom: Platform.OS === "ios" ? 20 : 8,
      paddingTop: theme.space.sm,
    },
    tabList: { flexDirection: "row", justifyContent: "space-around" },
    tabItem: {
      minWidth: 78,
      alignItems: "center",
      gap: theme.space.xs,
      paddingVertical: theme.space.xs,
    },
    tabItemActive: {},
    tabIcon: { color: theme.colors.textMuted, height: 22 },
    tabLabel: { color: theme.colors.textMuted, fontSize: 10, fontWeight: "700" },
    tabSafeArea: { flex: 1, backgroundColor: theme.colors.canvas },
    screenFrame: { flexGrow: 1, padding: theme.space.xl, paddingBottom: theme.space.xxxl },
    screenFrameDesktop: { padding: theme.space.xxxl },
    screenPage: { width: "100%", maxWidth: 900, alignSelf: "center" },
    operationRoute: { flex: 1, minHeight: 0 },
    operationToolbar: {
      height: 48,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: theme.space.lg,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.separator,
      backgroundColor: theme.colors.canvas,
    },
    operationToolbarTitle: {
      flex: 1,
      color: theme.colors.text,
      fontSize: 15,
      fontWeight: "700",
    },
    operationToolbarButton: {
      width: 34,
      height: 34,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 7,
    },
    operationFrame: { flexGrow: 1, padding: theme.space.xl, paddingBottom: theme.space.xxxl },
    operationFrameDesktop: {
      paddingHorizontal: theme.space.giant,
      paddingVertical: theme.space.huge,
    },
    rootOperation: { flex: 1, backgroundColor: theme.colors.canvas },
    fullScreenOperation: { flexGrow: 1, padding: theme.space.xl, paddingBottom: theme.space.xl },
    nativeMemorySearch: {
      height: 50,
      flexDirection: "row",
      alignItems: "center",
      gap: theme.space.md,
      marginHorizontal: theme.space.xl,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.separatorStrong,
    },
    nativeMemorySearchInput: {
      flex: 1,
      color: theme.colors.text,
      fontSize: 15,
      paddingVertical: theme.space.md,
    },
    webStackHeader: {
      minHeight: 58,
      flexDirection: "row",
      alignItems: "center",
      gap: theme.space.md,
      paddingHorizontal: theme.space.xl,
      backgroundColor: theme.colors.canvas,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.separator,
    },
    webBackButton: {
      width: 36,
      height: 44,
      alignItems: "flex-start",
      justifyContent: "center",
    },
    webHeaderTitle: { color: theme.colors.text, fontSize: 16, fontWeight: "700" },
    webHeaderSearch: {
      flex: 1,
      maxWidth: 820,
      height: 44,
      flexDirection: "row",
      alignItems: "center",
      gap: theme.space.md,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.separatorStrong,
    },
    webHeaderSearchInput: {
      flex: 1,
      color: theme.colors.text,
      fontSize: 15,
      paddingVertical: theme.space.md,
    },
    moreScreen: {
      flexGrow: 1,
      paddingHorizontal: theme.space.xl,
      paddingTop: theme.space.xxl,
      paddingBottom: theme.space.giant,
    },
    moreSection: { marginBottom: theme.space.xl },
    moreSectionLabel: {
      color: theme.colors.accent,
      fontSize: 10,
      fontWeight: "800",
      letterSpacing: 1.4,
      textTransform: "uppercase",
      marginBottom: theme.space.xs,
    },
    moreRow: {
      minHeight: 58,
      flexDirection: "row",
      alignItems: "center",
      gap: theme.space.md,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.separator,
    },
    moreIcon: { color: theme.colors.textSecondary, width: 24 },
    moreRowText: { flex: 1 },
    moreTitle: { color: theme.colors.text, fontSize: 14, fontWeight: "700" },
    moreDescription: { color: theme.colors.textMuted, fontSize: 11, marginTop: theme.space.xs },
    moreChevron: { color: theme.colors.textMuted },
    mobileSignOut: {
      minHeight: 52,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: theme.space.sm,
      marginTop: theme.space.lg,
      borderWidth: 1,
      borderColor: theme.colors.danger,
      borderRadius: 12,
    },
    mobileSignOutText: { color: theme.colors.danger, fontSize: 13, fontWeight: "800" },
  });
