import { StyleSheet } from "react-native";
import type { VitoTheme } from "../../hooks/useVitoTheme";

export const createVoiceStyles = (theme: VitoTheme) =>
  StyleSheet.create({
    root: { flex: 1, width: "100%", alignItems: "center" },
    voiceStage: { flex: 1, minHeight: 390, alignItems: "center", justifyContent: "center" },
    eyebrow: {
      alignSelf: "flex-start",
      color: theme.colors.accent,
      fontSize: 9,
      fontWeight: "800",
      letterSpacing: 1.8,
    },
    title: {
      alignSelf: "flex-start",
      color: theme.colors.text,
      fontSize: 34,
      fontWeight: "800",
      letterSpacing: -1.2,
      marginTop: theme.space.xs,
    },
    subtitle: {
      alignSelf: "flex-start",
      color: theme.colors.textMuted,
      fontSize: 14,
      lineHeight: 20,
      marginTop: theme.space.sm,
      maxWidth: 500,
    },
    backToHistory: {
      color: theme.colors.accent,
      fontSize: 12,
      fontWeight: "700",
      marginTop: theme.space.md,
    },
    connecting: { marginTop: theme.space.xl },
    voicePicker: { width: "100%", marginTop: theme.space.xxl, gap: theme.space.sm },
    voicePickerLabel: {
      color: theme.colors.textMuted,
      fontSize: 9,
      fontWeight: "800",
      letterSpacing: 1.2,
    },
    voiceOptions: { flexDirection: "row", gap: theme.space.sm },
    voiceOption: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.colors.separatorStrong,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: theme.space.lg,
      paddingVertical: theme.space.sm,
      flexDirection: "row",
      alignItems: "center",
      gap: theme.space.sm,
    },
    voiceOptionSelected: { backgroundColor: theme.colors.accent, borderColor: theme.colors.accent },
    voiceOptionText: { color: theme.colors.textSecondary, fontSize: 12, fontWeight: "700" },
    voiceOptionTextSelected: { color: theme.colors.accentText },
    previewIcon: { color: theme.colors.textMuted, fontSize: 10 },
    orb: {
      width: 196,
      height: 196,
      borderRadius: 98,
      backgroundColor: theme.colors.surfaceRaised,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: theme.colors.separatorStrong,
    },
    orbActive: { backgroundColor: theme.colors.accent, borderColor: theme.colors.accent },
    orbConnecting: { opacity: 0.8 },
    orbSpeaking: {
      transform: [{ scale: 1.07 }],
      shadowColor: theme.colors.accent,
      shadowOpacity: 0.4,
      shadowRadius: 28,
    },
    orbMark: { color: theme.colors.accent, fontSize: 58, fontWeight: "900" },
    orbMarkActive: { color: theme.colors.accentText, fontSize: 30 },
    state: {
      color: theme.colors.textSecondary,
      fontSize: 15,
      fontWeight: "700",
      marginTop: theme.space.xl,
    },
    error: {
      color: theme.colors.danger,
      fontSize: 12,
      lineHeight: 17,
      textAlign: "center",
      marginTop: theme.space.md,
      maxWidth: 340,
    },
    taskStack: { width: "100%", gap: theme.space.sm, marginTop: theme.space.lg },
    taskCard: {
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.separatorStrong,
      borderRadius: 13,
      padding: theme.space.md,
    },
    taskHeader: { flexDirection: "row", alignItems: "center", gap: theme.space.sm },
    taskIcon: { fontSize: 14 },
    taskStatus: { color: theme.colors.text, fontSize: 12, fontWeight: "800" },
    taskQuestion: { color: theme.colors.textMuted, fontSize: 11, marginTop: theme.space.sm },
    taskHint: {
      color: theme.colors.accent,
      fontSize: 11,
      fontWeight: "700",
      marginTop: theme.space.sm,
    },
    historyButton: {
      minHeight: 48,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: theme.space.xl,
      marginBottom: theme.space.md,
    },
    historyButtonText: { color: theme.colors.accent, fontSize: 13, fontWeight: "800" },
    resumeButton: {
      backgroundColor: theme.colors.accent,
      borderRadius: 12,
      paddingHorizontal: theme.space.xl,
      paddingVertical: theme.space.md,
      marginTop: theme.space.lg,
    },
    resumeButtonText: { color: theme.colors.accentText, fontSize: 13, fontWeight: "800" },
    controls: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "center",
      gap: theme.space.md,
      marginTop: theme.space.xxl,
    },
    primaryButton: {
      minWidth: 140,
      height: 50,
      borderRadius: 15,
      backgroundColor: theme.colors.accent,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: theme.space.xl,
    },
    stopButton: { backgroundColor: theme.colors.danger },
    primaryText: { color: theme.colors.accentText, fontSize: 14, fontWeight: "800" },
    secondaryButton: {
      minWidth: 100,
      height: 50,
      borderRadius: 15,
      backgroundColor: theme.colors.surfaceRaised,
      borderWidth: 1,
      borderColor: theme.colors.separatorStrong,
      alignItems: "center",
      justifyContent: "center",
    },
    secondaryText: { color: theme.colors.textSecondary, fontSize: 14, fontWeight: "700" },
    transcript: {
      width: "100%",
      marginTop: theme.space.xxxl,
      borderTopWidth: 1,
      borderTopColor: theme.colors.separator,
    },
    transcriptContent: { paddingVertical: theme.space.lg, gap: theme.space.md },
    historyBlock: { gap: theme.space.md, marginBottom: theme.space.xs },
    historyTitle: {
      color: theme.colors.textMuted,
      fontSize: 9,
      fontWeight: "800",
      letterSpacing: 1.2,
    },
    historyRow: { flexDirection: "row", gap: theme.space.sm },
    historyListRow: {
      minHeight: 62,
      flexDirection: "row",
      alignItems: "center",
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.separator,
      paddingVertical: theme.space.md,
    },
    historyListCopy: { flex: 1, minWidth: 0 },
    historyListTitle: { color: theme.colors.text, fontSize: 13, fontWeight: "700" },
    historyChevron: { color: theme.colors.textMuted, fontSize: 24 },
    historyCard: {
      minWidth: 112,
      backgroundColor: theme.colors.surface,
      borderColor: theme.colors.separator,
      borderWidth: 1,
      borderRadius: 12,
      padding: theme.space.md,
    },
    historyDate: { color: theme.colors.textSecondary, fontSize: 12, fontWeight: "700" },
    historyTime: { color: theme.colors.textMuted, fontSize: 11, marginTop: theme.space.xs },
    summary: { color: theme.colors.textSecondary, fontSize: 11, textAlign: "center" },
    line: {
      padding: theme.space.lg,
      borderRadius: 14,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.separator,
    },
    role: {
      color: theme.colors.accent,
      fontSize: 9,
      fontWeight: "800",
      letterSpacing: 1.2,
      marginBottom: theme.space.xs,
      textTransform: "uppercase",
    },
    lineText: { color: theme.colors.textSecondary, fontSize: 14, lineHeight: 20 },
  });
