import { StyleSheet } from "react-native";
import type { VitoTheme } from "../../hooks/useVitoTheme";

export const createSecretsStyles = (theme: VitoTheme) =>
  StyleSheet.create({
    workspace: { flex: 1 },
    workspaceHeader: {
      height: 48,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: theme.space.lg,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.separator,
    },
    workspaceHeading: { flex: 1, flexDirection: "row", alignItems: "center", gap: theme.space.sm },
    workspaceTitle: { flex: 1, color: theme.colors.text, fontSize: 15, fontWeight: "700" },
    workspaceBody: { flex: 1 },
    desktopBack: { width: 34, height: 34, alignItems: "center", justifyContent: "center" },
    desktopAdd: {
      width: 40,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 20,
      backgroundColor: theme.colors.accentSurface,
    },
    center: { flex: 1, alignItems: "center", justifyContent: "center" },
    list: { paddingHorizontal: theme.space.lg, paddingBottom: theme.space.xxxl },
    sectionTitle: {
      color: theme.colors.textMuted,
      fontSize: 9,
      fontWeight: "900",
      letterSpacing: 1.2,
      textTransform: "uppercase",
      paddingTop: theme.space.xl,
      paddingBottom: theme.space.sm,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.separator,
    },
    customSection: { marginTop: theme.space.lg },
    empty: {
      color: theme.colors.textMuted,
      fontSize: 12,
      textAlign: "center",
      paddingVertical: theme.space.xxl,
    },
    row: {
      minHeight: 76,
      flexDirection: "row",
      alignItems: "center",
      gap: theme.space.md,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.separator,
      paddingVertical: theme.space.md,
    },
    rowMain: { flex: 1 },
    key: { color: theme.colors.text, fontFamily: "monospace", fontSize: 13, fontWeight: "800" },
    description: { color: theme.colors.textMuted, fontSize: 11, lineHeight: 16, marginTop: 4 },
    masked: { color: theme.colors.textMuted, fontSize: 11, letterSpacing: 1.5, marginTop: 5 },
    notSet: { color: theme.colors.warning, fontSize: 10, fontWeight: "800", marginTop: 5 },
    editor: {
      padding: theme.space.xl,
      paddingBottom: theme.space.xxxl,
      maxWidth: 640,
      width: "100%",
    },
    editorDescription: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      paddingBottom: theme.space.lg,
      marginBottom: theme.space.xl,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.separator,
    },
    field: { marginBottom: theme.space.xl },
    label: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      fontWeight: "800",
      marginBottom: theme.space.sm,
    },
    valueHeading: { flexDirection: "row", justifyContent: "space-between" },
    input: {
      color: theme.colors.text,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.separatorStrong,
      borderRadius: 11,
      paddingHorizontal: theme.space.md,
      paddingVertical: theme.space.md,
      fontFamily: "monospace",
    },
    inputLocked: { color: theme.colors.textMuted, backgroundColor: theme.colors.canvas },
    valueInput: { minHeight: 110, textAlignVertical: "top" },
    help: { color: theme.colors.textMuted, fontSize: 10, marginTop: theme.space.xs },
    reveal: { color: theme.colors.accent, fontSize: 11, fontWeight: "800" },
    saveButton: {
      alignItems: "center",
      backgroundColor: theme.colors.accent,
      borderRadius: 11,
      padding: theme.space.md,
    },
    saveText: { color: theme.colors.accentText, fontWeight: "900" },
    disabled: { opacity: 0.45 },
    deleteButton: { alignItems: "center", marginTop: theme.space.lg, padding: theme.space.md },
    deleteText: { color: theme.colors.danger, fontWeight: "800" },
    error: { color: theme.colors.danger, marginBottom: theme.space.md },
  });
