import { StyleSheet } from "react-native";
import type { VitoTheme } from "../../hooks/useVitoTheme";

export const createSettingsStyles = (theme: VitoTheme) =>
  StyleSheet.create({
    root: { flex: 1 },
    loading: { flex: 1, alignItems: "center", justifyContent: "center" },
    header: {
      height: 58,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: theme.space.xl,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.separator,
    },
    title: { color: theme.colors.text, fontSize: 20, fontWeight: "800" },
    inlineStatus: {
      position: "absolute",
      right: theme.space.xl,
      top: theme.space.md,
      zIndex: 2,
      color: theme.colors.textMuted,
      fontSize: 11,
    },
    status: { color: theme.colors.textMuted, fontSize: 11 },
    saved: { color: theme.colors.success, fontSize: 11, fontWeight: "700" },
    tabs: {
      flexDirection: "row",
      paddingHorizontal: theme.space.lg,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.separator,
    },
    tab: {
      paddingHorizontal: theme.space.md,
      paddingVertical: theme.space.md,
      borderBottomWidth: 2,
      borderBottomColor: "transparent",
    },
    tabActive: { borderBottomColor: theme.colors.accent },
    tabText: { color: theme.colors.textMuted, fontWeight: "700" },
    tabTextActive: { color: theme.colors.accent },
    content: {
      padding: theme.space.xl,
      paddingBottom: theme.space.xxxl,
      maxWidth: 720,
      width: "100%",
    },
    section: {
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.separator,
      borderRadius: 14,
      padding: theme.space.lg,
      marginBottom: theme.space.lg,
    },
    sectionTitle: {
      color: theme.colors.text,
      fontSize: 14,
      fontWeight: "800",
      marginBottom: theme.space.xs,
    },
    sectionSubtitle: { color: theme.colors.textMuted, fontSize: 11, marginBottom: theme.space.md },
    row: {
      paddingVertical: theme.space.md,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.separator,
    },
    rowOverridden: {
      borderLeftWidth: 2,
      borderLeftColor: theme.colors.accent,
      paddingLeft: theme.space.md,
    },
    rowHeading: { flexDirection: "row", alignItems: "flex-start", marginBottom: theme.space.sm },
    label: { color: theme.colors.textSecondary, fontSize: 13, fontWeight: "700" },
    overrideLabel: {
      color: theme.colors.accent,
      fontSize: 8,
      fontWeight: "900",
      letterSpacing: 0.8,
      backgroundColor: theme.colors.accentSurface,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 4,
      overflow: "hidden",
    },
    hint: { color: theme.colors.textMuted, fontSize: 10, marginTop: 2 },
    reset: { color: theme.colors.danger, fontSize: 11 },
    input: {
      color: theme.colors.text,
      backgroundColor: theme.colors.canvas,
      borderWidth: 1,
      borderColor: theme.colors.separatorStrong,
      borderRadius: 9,
      paddingHorizontal: theme.space.md,
      paddingVertical: theme.space.sm,
    },
    textarea: { minHeight: 90, textAlignVertical: "top" },
    segments: { flexDirection: "row", flexWrap: "wrap", gap: theme.space.xs },
    segment: {
      borderWidth: 1,
      borderColor: theme.colors.separatorStrong,
      borderRadius: 8,
      paddingHorizontal: theme.space.md,
      paddingVertical: theme.space.sm,
    },
    segmentActive: {
      backgroundColor: theme.colors.accentSurface,
      borderColor: theme.colors.accent,
    },
    segmentText: { color: theme.colors.textMuted, fontSize: 11, fontWeight: "700" },
    segmentTextActive: { color: theme.colors.accent },
    choice: {
      padding: theme.space.md,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.separator,
    },
    choiceActive: { backgroundColor: theme.colors.accentSurface },
    choiceText: { color: theme.colors.textSecondary },
    choiceTextActive: { color: theme.colors.accent, fontWeight: "800" },
    select: {
      minHeight: 42,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: theme.space.md,
      backgroundColor: theme.colors.canvas,
      borderWidth: 1,
      borderColor: theme.colors.separatorStrong,
      borderRadius: 9,
      paddingHorizontal: theme.space.md,
    },
    selectText: { flex: 1, color: theme.colors.text, fontSize: 13 },
    chevron: { color: theme.colors.textMuted, fontSize: 18 },
    modalBackdrop: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,.65)",
      alignItems: "center",
      justifyContent: "center",
      padding: theme.space.xl,
    },
    modalCard: {
      width: "100%",
      maxWidth: 520,
      maxHeight: "70%",
      backgroundColor: theme.colors.surfaceRaised,
      borderWidth: 1,
      borderColor: theme.colors.separatorStrong,
      borderRadius: 16,
      overflow: "hidden",
    },
    modalTitle: {
      color: theme.colors.text,
      fontSize: 16,
      fontWeight: "800",
      padding: theme.space.lg,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.separator,
    },
    option: {
      minHeight: 48,
      flexDirection: "row",
      alignItems: "center",
      gap: theme.space.md,
      paddingHorizontal: theme.space.lg,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.separator,
    },
    optionActive: { backgroundColor: theme.colors.accentSurface },
    optionText: { flex: 1, color: theme.colors.textSecondary, fontSize: 13 },
    optionTextActive: { color: theme.colors.accent, fontWeight: "800" },
    optionGroup: {
      color: theme.colors.textMuted,
      fontSize: 9,
      fontWeight: "900",
      letterSpacing: 1.1,
      textTransform: "uppercase",
      paddingHorizontal: theme.space.lg,
      paddingTop: theme.space.lg,
      paddingBottom: theme.space.sm,
    },
    optionBadge: { color: theme.colors.accent, fontSize: 9, marginTop: 3 },
    sessionMeta: {
      flexDirection: "row",
      alignItems: "center",
      gap: theme.space.sm,
      marginTop: theme.space.md,
    },
    sessionChannel: { color: theme.colors.accent, fontSize: 10, fontWeight: "900" },
    overrideBadge: {
      color: theme.colors.accent,
      backgroundColor: theme.colors.accentSurface,
      fontSize: 10,
      paddingHorizontal: theme.space.sm,
      paddingVertical: 3,
      borderRadius: 99,
      overflow: "hidden",
    },
    inheritBadge: {
      color: theme.colors.textMuted,
      backgroundColor: theme.colors.canvas,
      fontSize: 10,
      paddingHorizontal: theme.space.sm,
      paddingVertical: 3,
      borderRadius: 99,
      overflow: "hidden",
    },
    check: { color: theme.colors.accent, fontSize: 16, fontWeight: "800" },
    actionButton: {
      alignSelf: "flex-start",
      marginTop: theme.space.sm,
      borderWidth: 1,
      borderColor: theme.colors.accent,
      borderRadius: 9,
      paddingHorizontal: theme.space.md,
      paddingVertical: theme.space.sm,
      backgroundColor: theme.colors.accentSurface,
    },
    actionDisabled: { opacity: 0.45 },
    actionButtonText: { color: theme.colors.accent, fontSize: 11, fontWeight: "800" },
    actionSuccess: { color: theme.colors.success, fontSize: 12, marginVertical: theme.space.sm },
    idWrap: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: theme.space.xs,
      marginTop: theme.space.sm,
    },
    idChip: {
      backgroundColor: theme.colors.accentSurface,
      borderWidth: 1,
      borderColor: theme.colors.accent,
      borderRadius: 7,
      paddingHorizontal: theme.space.sm,
      paddingVertical: 5,
    },
    idText: { color: theme.colors.accent, fontFamily: "monospace", fontSize: 10 },
    idAdd: { flexDirection: "row", gap: theme.space.sm, marginTop: theme.space.sm },
    addButton: {
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.accentSurface,
      borderRadius: 9,
      paddingHorizontal: theme.space.lg,
    },
    addButtonText: { color: theme.colors.accent, fontWeight: "800", fontSize: 11 },
    resetAllButton: {
      alignSelf: "flex-start",
      borderWidth: 1,
      borderColor: theme.colors.danger,
      borderRadius: 9,
      paddingHorizontal: theme.space.md,
      paddingVertical: theme.space.sm,
      marginBottom: theme.space.lg,
    },
    resetAllText: { color: theme.colors.danger, fontSize: 11, fontWeight: "800" },
    muted: { color: theme.colors.textMuted },
    error: { color: theme.colors.danger, marginBottom: theme.space.md },
  });
