import { Platform, StyleSheet } from "react-native";
import type { VitoTheme } from "../../hooks/useVitoTheme";

export const createChatStyles = (theme: VitoTheme) =>
  StyleSheet.create({
    desktopRoot: { flex: 1, flexDirection: "row", backgroundColor: theme.colors.canvas },
    desktopList: { width: 340, flexShrink: 0 },
    desktopConversation: {
      flex: 1,
      minWidth: 0,
      borderLeftWidth: 1,
      borderLeftColor: theme.colors.separator,
    },
    listRoot: { flex: 1, backgroundColor: theme.colors.canvas },
    sessionToolbar: {
      minHeight: 43,
      alignItems: "flex-end",
      justifyContent: "center",
      paddingHorizontal: theme.space.md,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.separator,
    },
    sessionFilterButton: {
      width: 34,
      height: 34,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 7,
    },
    sessionFilterBadge: {
      position: "absolute",
      top: 1,
      right: 0,
      minWidth: 14,
      height: 14,
      paddingHorizontal: 3,
      borderRadius: 7,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.accent,
    },
    sessionFilterBadgeText: { color: theme.colors.accentText, fontSize: 8, fontWeight: "900" },
    filterBackdrop: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      padding: theme.space.lg,
      backgroundColor: "rgba(0,0,0,0.55)",
    },
    filterModal: {
      width: "100%",
      maxWidth: 420,
      maxHeight: "80%",
      padding: theme.space.lg,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.colors.separatorStrong,
      backgroundColor: theme.colors.surface,
    },
    filterModalHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: theme.space.md,
    },
    filterModalTitle: { color: theme.colors.text, fontSize: 17, fontWeight: "800" },
    filterRow: {
      minHeight: 44,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.separator,
    },
    filterRowText: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      fontWeight: "600",
      textTransform: "capitalize",
    },
    showAllButton: { alignSelf: "flex-start", paddingTop: theme.space.lg },
    showAllButtonText: { color: theme.colors.accent, fontSize: 13, fontWeight: "700" },
    sessionList: { paddingLeft: theme.space.lg, paddingTop: theme.space.sm },
    listLoader: { marginTop: theme.space.giant },
    emptySessionFilter: { alignItems: "center", gap: theme.space.sm, padding: theme.space.giant },
    clearSessionFilters: { color: theme.colors.accent, fontSize: 13, fontWeight: "700" },
    sessionRow: {
      minHeight: 76,
      flexDirection: "row",
      alignItems: "center",
      gap: theme.space.md,
      paddingRight: theme.space.md,
    },
    sessionRowActive: { backgroundColor: theme.colors.accentSurface },
    avatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: theme.colors.accentSurface,
      alignItems: "center",
      justifyContent: "center",
    },
    avatarText: { color: theme.colors.accent, fontWeight: "800", fontSize: 17 },
    sessionBody: {
      flex: 1,
      minWidth: 0,
      alignSelf: "stretch",
      justifyContent: "center",
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.separator,
    },
    sessionTop: { flexDirection: "row", alignItems: "center", gap: theme.space.sm },
    sessionName: { flex: 1, color: theme.colors.text, fontSize: 15, fontWeight: "700" },
    sessionTime: { color: theme.colors.textMuted, fontSize: 11 },
    chevron: { color: theme.colors.textMuted, fontSize: 20 },
    sessionPreview: { color: theme.colors.textMuted, fontSize: 12, marginTop: theme.space.xs },
    conversationRoot: {
      flex: 1,
      minHeight: 0,
      backgroundColor: theme.colors.canvas,
      overflow: "hidden",
    },
    conversationHeader: {
      height: 50,
      flexDirection: "row",
      alignItems: "center",
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.separator,
      backgroundColor: theme.colors.sidebar,
    },
    headerButton: { width: 50, height: 50, alignItems: "center", justifyContent: "center" },
    hidden: { opacity: 0 },
    conversationTitle: {
      flex: 1,
      color: theme.colors.text,
      fontSize: 16,
      fontWeight: "700",
      textAlign: "center",
    },
    menu: {
      position: "absolute",
      zIndex: 20,
      top: 50,
      right: 10,
      width: 218,
      paddingHorizontal: theme.space.lg,
      borderRadius: 14,
      backgroundColor: theme.colors.surfaceRaised,
      borderWidth: 1,
      borderColor: theme.colors.separatorStrong,
      shadowColor: "#000",
      shadowOpacity: 0.45,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 8 },
      elevation: 12,
    },
    menuRow: {
      minHeight: 53,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    menuLabel: { color: theme.colors.text, fontSize: 14, fontWeight: "600" },
    menuRule: { height: 1, backgroundColor: theme.colors.separatorStrong },
    toggleTrack: {
      width: 44,
      height: 26,
      borderRadius: 14,
      backgroundColor: theme.colors.surfaceRaised,
      padding: theme.space.xxs,
    },
    toggleTrackOn: { backgroundColor: theme.colors.accent },
    toggleThumb: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: theme.colors.text,
    },
    toggleThumbOn: { alignSelf: "flex-end" },
    messages: { flex: 1, minHeight: 0 },
    messageContent: {
      paddingHorizontal: theme.space.md,
      paddingVertical: theme.space.xl,
      gap: theme.space.sm,
      flexGrow: 1,
      justifyContent: "flex-end",
    },
    loader: { marginVertical: theme.space.giant },
    empty: { flex: 1, alignItems: "center", justifyContent: "center" },
    emptyTitle: { color: theme.colors.textSecondary, fontWeight: "700", fontSize: 16 },
    emptyText: { color: theme.colors.textMuted, fontSize: 12, marginTop: theme.space.xs },
    messageRow: { flexDirection: "row" },
    userRow: { justifyContent: "flex-end" },
    bubble: {
      maxWidth: "82%",
      borderRadius: 19,
      paddingHorizontal: theme.space.md,
      paddingVertical: theme.space.sm,
    },
    desktopBubble: { maxWidth: 680 },
    desktopAttachmentBubble: { width: 480 },
    assistantBubble: { backgroundColor: theme.colors.separator, borderBottomLeftRadius: 5 },
    attachments: { gap: theme.space.sm, marginTop: theme.space.sm },
    attachmentLoader: { marginVertical: theme.space.xl },
    attachmentError: { color: theme.colors.danger, fontSize: 12 },
    attachmentImage: {
      width: "100%",
      maxHeight: 420,
      borderRadius: theme.radius.md,
      backgroundColor: theme.colors.canvas,
    },
    attachmentFile: {
      flexDirection: "row",
      alignItems: "center",
      gap: theme.space.sm,
      paddingVertical: theme.space.sm,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.colors.separatorStrong,
    },
    attachmentFileIcon: { color: theme.colors.accent },
    attachmentFileBody: { flex: 1, minWidth: 0 },
    attachmentFileName: { color: theme.colors.text, fontSize: 13, fontWeight: "700" },
    attachmentFileType: { color: theme.colors.textMuted, fontSize: 11, marginTop: theme.space.xxs },
    userBubble: { backgroundColor: theme.colors.accent, borderBottomRightRadius: 5 },
    thoughtCard: {
      maxWidth: "88%",
      alignSelf: "flex-start",
      borderRadius: 13,
      padding: theme.space.md,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.separatorStrong,
    },
    toolCard: {
      width: "92%",
      maxWidth: "92%",
      minWidth: 0,
      overflow: "hidden",
      alignSelf: "flex-start",
      borderRadius: 13,
      padding: theme.space.md,
      backgroundColor: theme.colors.infoSurface,
      borderWidth: 1,
      borderColor: theme.colors.info,
    },
    toolResponseCard: {
      backgroundColor: theme.colors.successSurface,
      borderColor: theme.colors.success,
    },
    specialHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: theme.space.md,
    },
    thoughtLabel: { color: theme.colors.accent, fontSize: 10, fontWeight: "900", letterSpacing: 1 },
    toolLabel: { color: theme.colors.info, fontSize: 10, fontWeight: "900", letterSpacing: 1 },
    toolResponseLabel: { color: theme.colors.success },
    thoughtBody: { marginTop: theme.space.sm },
    specialTime: {
      flexShrink: 1,
      color: theme.colors.textMuted,
      fontSize: 9,
      fontWeight: "700",
      textTransform: "uppercase",
    },
    toolBranch: {
      marginTop: theme.space.xs,
      marginLeft: theme.space.sm,
      paddingLeft: theme.space.sm,
      borderLeftWidth: 1,
      borderLeftColor: theme.colors.separatorStrong,
    },
    toolBody: { marginTop: theme.space.sm },
    toolMode: {
      color: theme.colors.accent,
      fontSize: 9,
      fontWeight: "900",
      letterSpacing: 0.8,
    },
    toolRaw: {
      color: theme.colors.textSecondary,
      fontSize: 11,
      lineHeight: 16,
      fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    },
    toolField: { marginTop: theme.space.sm },
    toolKey: {
      color: theme.colors.textMuted,
      fontSize: 10,
      fontWeight: "800",
      marginBottom: theme.space.xxs,
      fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    },
    toolMarkdown: { width: "100%", maxWidth: "100%", minWidth: 0, overflow: "hidden" },
    toolPrimitive: {
      color: theme.colors.textSecondary,
      fontSize: 11,
      lineHeight: 16,
      fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    },
    error: {
      color: theme.colors.danger,
      fontSize: 11,
      paddingHorizontal: theme.space.md,
      paddingVertical: theme.space.xs,
    },
    composer: {
      flexDirection: "row",
      alignItems: "flex-end",
      gap: theme.space.sm,
      marginHorizontal: theme.space.md,
      marginVertical: theme.space.sm,
      minHeight: 44,
      paddingLeft: theme.space.lg,
      paddingRight: theme.space.xs,
      paddingVertical: theme.space.xs,
      borderRadius: 23,
      borderWidth: 1,
      borderColor: theme.colors.separatorStrong,
      backgroundColor: theme.colors.surface,
    },
    composerWeb: { alignItems: "center" },
    input: {
      flex: 1,
      maxHeight: 112,
      minHeight: 34,
      color: theme.colors.text,
      fontSize: 15,
      paddingTop: theme.space.sm,
      paddingBottom: theme.space.sm,
    },
    inputWeb: {
      minHeight: 22,
      lineHeight: 20,
      paddingTop: theme.space.none,
      paddingBottom: theme.space.none,
      outlineWidth: 0,
    },
    send: {
      width: 35,
      height: 35,
      borderRadius: 18,
      backgroundColor: theme.colors.accent,
      alignItems: "center",
      justifyContent: "center",
    },
    sendDisabled: { opacity: 0.32 },
  });
